CREATE OR REPLACE DATABASE DEV;
USE DEV.PUBLIC;
CREATE SCHEMA IF NOT EXISTS BIZ;

CREATE  OR REPLACE DATABASE SIT;
USE SIT.PUBLIC;
CREATE SCHEMA IF NOT EXISTS BIZ;


CREATE  OR REPLACE DATABASE UAT;
USE UAT.PUBLIC;
CREATE SCHEMA IF NOT EXISTS BIZ;


CREATE  OR REPLACE DATABASE PRD;
USE PRD.PUBLIC;
CREATE SCHEMA IF NOT EXISTS BIZ;


CREATE  OR REPLACE DATABASE LAB_PRELOADED;
USE LAB_PRELOADED.PUBLIC;
CREATE SCHEMA IF NOT EXISTS LAB_PRELOADED;

